export const Notifications = {
    MEMBER_REMOVED: "MEMBER_REMOVED",
    MEMBER_JOINED: "MEMBER_JOINED",
    MEMBER_ROLE_CHANGED: "MEMBER_ROLE_CHANGED",

    WORKSPACE_NAME_CHANGED: "WORKSPACE_NAME_CHANGED",
    WORKSPACE_DELETED: "WORKSPACE_DELETED",

    PROJECT_CREATED:"PROJECT_CREATED",
    PROJECT_NAME_CHANGED:"PROJECT_NAME_CHANGED",
    PROJECT_DELETED:"PROJECT_DELETED",

    TASK_ASSIGNED: "TASK_ASSIGNED",
    TASK_UNASSIGNED:"TASK_UNASSIGNED",
    TASK_STATUS_CHANGED:"TASK_STATUS_CHANGED",
    TASK_DELETED:"TASK_DELETED",
    // Add other notification types as needed
}as const;

export type NotificationTypeEnum = keyof typeof Notification;
